// default package
// Generated 08-nov-2016 19:34:56 by Hibernate Tools 4.0.0.Final
package entidades;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.annotation.*;

/**
 * Editorial generated by hbm2java
 */
@Entity
@Table(name = "editorial", catalog = "tiendaonlinefinal")
public class Editorial implements java.io.Serializable {

	private Integer idEditorial;
	private Libro libro;
	private String nombre;

	public Editorial() {
	}

	public Editorial(Libro libro, String nombre) {
		this.libro = libro;
		this.nombre = nombre;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idEditorial", unique = true, nullable = false)
	public Integer getIdEditorial() {
		return this.idEditorial;
	}

	public void setIdEditorial(Integer idEditorial) {
		this.idEditorial = idEditorial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLibro", nullable = false)
	public Libro getLibro() {
		return this.libro;
	}

	public void setLibro(Libro libro) {
		this.libro = libro;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
